export const useCountries = () => [
  {
    NameEnUS: 'Afghanistan',
    nameFaIR: 'افغانستان',
    code: 'AF',
    dial_code: '+93',
  },
  {
    NameEnUS: 'Albania',
    nameFaIR: 'البانیا',
    code: 'AL',
    dial_code: '+355',
  },
  {
    NameEnUS: 'Algeria',
    nameFaIR: 'الجزایر',
    code: 'DZ',
    dial_code: '+213',
  },
  {
    NameEnUS: 'Andorra',
    nameFaIR: 'آندورا',
    code: 'AD',
    dial_code: '+376',
  },
  {
    NameEnUS: 'Angola',
    nameFaIR: 'آنگولا',
    code: 'AO',
    dial_code: '+244',
  },
  {
    NameEnUS: 'Antigua and Barbuda',
    nameFaIR: 'آنتیگوا و باربودا',
    code: 'AG',
    dial_code: '+1',
  },
  {
    NameEnUS: 'Argentina',
    nameFaIR: 'آرژانتین',
    code: 'AR',
    dial_code: '+54',
  },
  {
    NameEnUS: 'Armenia',
    nameFaIR: 'ارمنستان',
    code: 'AM',
    dial_code: '+374',
  },
  {
    NameEnUS: 'Australia',
    nameFaIR: 'استرالیا',
    code: 'AU',
    dial_code: '+61',
  },
  {
    NameEnUS: 'Austria',
    nameFaIR: 'اتریش',
    code: 'AT',
    dial_code: '+43',
  },
  {
    NameEnUS: 'Azerbaijan',
    nameFaIR: 'آذربایجان',
    code: 'AZ',
    dial_code: '+994',
  },
  {
    NameEnUS: 'Bahamas',
    nameFaIR: 'باهاما',
    code: 'BS',
    dial_code: '+1',
  },
  {
    NameEnUS: 'Bahrain',
    nameFaIR: 'بحرین',
    code: 'BH',
    dial_code: '+973',
  },
  {
    NameEnUS: 'Bangladesh',
    nameFaIR: 'بنگلادش',
    code: 'BD',
    dial_code: '+880',
  },
  {
    NameEnUS: 'Barbados',
    nameFaIR: 'باربادوس',
    code: 'BB',
    dial_code: '+1',
  },
  {
    NameEnUS: 'Belarus',
    nameFaIR: 'بلاروس',
    code: 'BY',
    dial_code: '+375',
  },
  {
    NameEnUS: 'Belgium',
    nameFaIR: 'بلژیک',
    code: 'BE',
    dial_code: '+32',
  },
  {
    NameEnUS: 'Belize',
    nameFaIR: 'بلیز',
    code: 'BZ',
    dial_code: '+501',
  },
  {
    NameEnUS: 'Benin',
    nameFaIR: 'بنین',
    code: 'BJ',
    dial_code: '+229',
  },
  {
    NameEnUS: 'Bhutan',
    nameFaIR: 'بوتان',
    code: 'BT',
    dial_code: '+975',
  },
  {
    NameEnUS: 'Bolivia',
    nameFaIR: 'بولیوی',
    code: 'BO',
    dial_code: '+591',
  },
  {
    NameEnUS: 'Bosnia and Herzegovina',
    nameFaIR: 'بوسنی و هرزگوین',
    code: 'BA',
    dial_code: '+387',
  },
  {
    NameEnUS: 'Botswana',
    nameFaIR: 'بوتسوانا',
    code: 'BW',
    dial_code: '+267',
  },
  {
    NameEnUS: 'Brazil',
    nameFaIR: 'برزیل',
    code: 'BR',
    dial_code: '+55',
  },
  {
    NameEnUS: 'Brunei',
    nameFaIR: 'برونئی',
    code: 'BN',
    dial_code: '+673',
  },
  {
    NameEnUS: 'Bulgaria',
    nameFaIR: 'بلغارستان',
    code: 'BG',
    dial_code: '+359',
  },
  {
    NameEnUS: 'Burkina Faso',
    nameFaIR: 'بورکینافاسو',
    code: 'BF',
    dial_code: '+226',
  },
  {
    NameEnUS: 'Burundi',
    nameFaIR: 'بروندی',
    code: 'BI',
    dial_code: '+257',
  },
  {
    NameEnUS: 'Cabo Verde',
    nameFaIR: 'کیپ ورد',
    code: 'CV',
    dial_code: '+238',
  },
  {
    NameEnUS: 'Cambodia',
    nameFaIR: 'کامبوج',
    code: 'KH',
    dial_code: '+855',
  },
  {
    NameEnUS: 'Cameroon',
    nameFaIR: 'کامرون',
    code: 'CM',
    dial_code: '+237',
  },
  {
    NameEnUS: 'Canada',
    nameFaIR: 'کانادا',
    code: 'CA',
    dial_code: '+1',
  },
  {
    NameEnUS: 'Central African Republic',
    nameFaIR: 'جمهوری افریقای مرکزی',
    code: 'CF',
    dial_code: '+236',
  },
  {
    NameEnUS: 'Chad',
    nameFaIR: 'چاد',
    code: 'TD',
    dial_code: '+235',
  },
  {
    NameEnUS: 'Chile',
    nameFaIR: 'شیلی',
    code: 'CL',
    dial_code: '+56',
  },
  {
    NameEnUS: 'China',
    nameFaIR: 'چین',
    code: 'CN',
    dial_code: '+86',
  },
  {
    NameEnUS: 'Colombia',
    nameFaIR: 'کلمبیا',
    code: 'CO',
    dial_code: '+57',
  },
  {
    NameEnUS: 'Comoros',
    nameFaIR: 'کومور',
    code: 'KM',
    dial_code: '+269',
  },
  {
    NameEnUS: 'Congo (Congo-Brazzaville)',
    nameFaIR: 'کنگو (برازاویل)',
    code: 'CG',
    dial_code: '+242',
  },
  {
    NameEnUS: 'Costa Rica',
    nameFaIR: 'کاستاریکا',
    code: 'CR',
    dial_code: '+506',
  },
  {
    NameEnUS: 'Croatia',
    nameFaIR: 'کرواسی',
    code: 'HR',
    dial_code: '+385',
  },
  {
    NameEnUS: 'Cuba',
    nameFaIR: 'کوبا',
    code: 'CU',
    dial_code: '+53',
  },
  {
    NameEnUS: 'Cyprus',
    nameFaIR: 'قبرس',
    code: 'CY',
    dial_code: '+357',
  },
  {
    NameEnUS: 'Czechia (Czech Republic)',
    nameFaIR: 'جمهوری چک',
    code: 'CZ',
    dial_code: '+420',
  },
  {
    NameEnUS: 'Democratic Republic of the Congo',
    nameFaIR: 'جمهوری دموکراتیک کنگو',
    code: 'CD',
    dial_code: '+243',
  },
  {
    NameEnUS: 'Denmark',
    nameFaIR: 'دانمارک',
    code: 'DK',
    dial_code: '+45',
  },
  {
    NameEnUS: 'Djibouti',
    nameFaIR: 'جیبوتی',
    code: 'DJ',
    dial_code: '+253',
  },
  {
    NameEnUS: 'Dominica',
    nameFaIR: 'دومینیکا',
    code: 'DM',
    dial_code: '+1',
  },
  {
    NameEnUS: 'Dominican Republic',
    nameFaIR: 'جمهوری دومینیکن',
    code: 'DO',
    dial_code: '+1',
  },
  {
    NameEnUS: 'Ecuador',
    nameFaIR: 'اکوادور',
    code: 'EC',
    dial_code: '+593',
  },
  {
    NameEnUS: 'Egypt',
    nameFaIR: 'مصر',
    code: 'EG',
    dial_code: '+20',
  },
  {
    NameEnUS: 'El Salvador',
    nameFaIR: 'السالوادور',
    code: 'SV',
    dial_code: '+503',
  },
  {
    NameEnUS: 'Equatorial Guinea',
    nameFaIR: 'گینه استوایی',
    code: 'GQ',
    dial_code: '+240',
  },
  {
    NameEnUS: 'Eritrea',
    nameFaIR: 'اریتره',
    code: 'ER',
    dial_code: '+291',
  },
  {
    NameEnUS: 'Estonia',
    nameFaIR: 'استونی',
    code: 'EE',
    dial_code: '+372',
  },
  {
    NameEnUS: 'Eswatini(fmr.Swaziland)',
    nameFaIR: 'اسواتینی',
    code: 'SZ',
    dial_code: '+268',
  },
  {
    NameEnUS: 'Ethiopia',
    nameFaIR: 'اتیوپی',
    code: 'ET',
    dial_code: '+251',
  },
  {
    NameEnUS: 'Fiji',
    nameFaIR: 'فیجی',
    code: 'FJ',
    dial_code: '+679',
  },
  {
    NameEnUS: 'Finland',
    nameFaIR: 'فنلاند',
    code: 'FI',
    dial_code: '+358',
  },
  {
    NameEnUS: 'France',
    nameFaIR: 'فرانسه',
    code: 'FR',
    dial_code: '+33',
  },
  {
    NameEnUS: 'Gabon',
    nameFaIR: 'گابون',
    code: 'GA',
    dial_code: '+241',
  },
  {
    NameEnUS: 'Gambia',
    nameFaIR: 'گامبیا',
    code: 'GM',
    dial_code: '+220',
  },
  {
    NameEnUS: 'Georgia',
    nameFaIR: 'گرجستان',
    code: 'GE',
    dial_code: '+995',
  },
  {
    NameEnUS: 'Germany',
    nameFaIR: 'آلمان',
    code: 'DE',
    dial_code: '+49',
  },
  {
    NameEnUS: 'Ghana',
    nameFaIR: 'غنا',
    code: 'GH',
    dial_code: '+233',
  },
  {
    NameEnUS: 'Greece',
    nameFaIR: 'یونان',
    code: 'GR',
    dial_code: '+30',
  },
  {
    NameEnUS: 'Grenada',
    nameFaIR: 'گرناڈا',
    code: 'GD',
    dial_code: '+1',
  },
  {
    NameEnUS: 'Guatemala',
    nameFaIR: 'گواتمالا',
    code: 'GT',
    dial_code: '+502',
  },
  {
    NameEnUS: 'Guinea',
    nameFaIR: 'گینه',
    code: 'GN',
    dial_code: '+224',
  },
  {
    NameEnUS: 'Guinea-Bissau',
    nameFaIR: 'گینه بیسائو',
    code: 'GW',
    dial_code: '+245',
  },
  {
    NameEnUS: 'Guyana',
    nameFaIR: 'گویانا',
    code: 'GY',
    dial_code: '+592',
  },
  {
    NameEnUS: 'Haiti',
    nameFaIR: 'هائیتی',
    code: 'HT',
    dial_code: '+509',
  },
  {
    NameEnUS: 'Honduras',
    nameFaIR: 'هانڈورس',
    code: 'HN',
    dial_code: '+504',
  },
  {
    NameEnUS: 'Hungary',
    nameFaIR: 'مجارستان',
    code: 'HU',
    dial_code: '+36',
  },
  {
    NameEnUS: 'Iceland',
    nameFaIR: 'ایسلند',
    code: 'IS',
    dial_code: '+354',
  },
  {
    NameEnUS: 'India',
    nameFaIR: 'هند',
    code: 'IN',
    dial_code: '+91',
  },
  {
    NameEnUS: 'Indonesia',
    nameFaIR: 'اندونزی',
    code: 'ID',
    dial_code: '+62',
  },
  {
    NameEnUS: 'Iran',
    nameFaIR: 'ایران',
    code: 'IR',
    dial_code: '+98',
  },
  {
    NameEnUS: 'Iraq',
    nameFaIR: 'عراق',
    code: 'IQ',
    dial_code: '+964',
  },
  {
    NameEnUS: 'Ireland',
    nameFaIR: 'ایرلند',
    code: 'IE',
    dial_code: '+353',
  },
  {
    NameEnUS: 'Israel',
    nameFaIR: 'اسرائیل',
    code: 'IL',
    dial_code: '+972',
  },
  {
    NameEnUS: 'Italy',
    nameFaIR: 'ایتالیا',
    code: 'IT',
    dial_code: '+39',
  },
  {
    NameEnUS: 'Jamaica',
    nameFaIR: 'جمائیکا',
    code: 'JM',
    dial_code: '+1',
  },
  {
    NameEnUS: 'Japan',
    nameFaIR: 'ژاپن',
    code: 'JP',
    dial_code: '+81',
  },
  {
    NameEnUS: 'Jordan',
    nameFaIR: 'اردن',
    code: 'JO',
    dial_code: '+962',
  },
  {
    NameEnUS: 'Kazakhstan',
    nameFaIR: 'قزاقستان',
    code: 'KZ',
    dial_code: '+7',
  },
  {
    NameEnUS: 'Kenya',
    nameFaIR: 'کنیا',
    code: 'KE',
    dial_code: '+254',
  },
  {
    NameEnUS: 'Kiribati',
    nameFaIR: 'کیریباتی',
    code: 'KI',
    dial_code: '+686',
  },
  {
    NameEnUS: 'Kuwait',
    nameFaIR: 'کویت',
    code: 'KW',
    dial_code: '+965',
  },
  {
    NameEnUS: 'Kyrgyzstan',
    nameFaIR: 'قرقیزستان',
    code: 'KG',
    dial_code: '+996',
  },
  {
    NameEnUS: 'Laos',
    nameFaIR: 'لائوس',
    code: 'LA',
    dial_code: '+856',
  },
  {
    NameEnUS: 'Latvia',
    nameFaIR: 'لتونی',
    code: 'LV',
    dial_code: '+371',
  },
  {
    NameEnUS: 'Lebanon',
    nameFaIR: 'لبنان',
    code: 'LB',
    dial_code: '+961',
  },
  {
    NameEnUS: 'Lesotho',
    nameFaIR: 'لسوتو',
    code: 'LS',
    dial_code: '+266',
  },
  {
    NameEnUS: 'Liberia',
    nameFaIR: 'لیبریا',
    code: 'LR',
    dial_code: '+231',
  },
  {
    NameEnUS: 'Libya',
    nameFaIR: 'لیبی',
    code: 'LY',
    dial_code: '+218',
  },
  {
    NameEnUS: 'Liechtenstein',
    nameFaIR: 'لیختن‌اشتاین',
    code: 'LI',
    dial_code: '+423',
  },
  {
    NameEnUS: 'Lithuania',
    nameFaIR: 'لیتوانی',
    code: 'LT',
    dial_code: '+370',
  },
  {
    NameEnUS: 'Luxembourg',
    nameFaIR: 'لوکزامبورگ',
    code: 'LU',
    dial_code: '+352',
  },
  {
    NameEnUS: 'Madagascar',
    nameFaIR: 'ماداگاسکار',
    code: 'MG',
    dial_code: '+261',
  },
  {
    NameEnUS: 'Malawi',
    nameFaIR: 'مالاوی',
    code: 'MW',
    dial_code: '+265',
  },
  {
    NameEnUS: 'Malaysia',
    nameFaIR: 'مالزی',
    code: 'MY',
    dial_code: '+60',
  },
  {
    NameEnUS: 'Maldives',
    nameFaIR: 'مالدیو',
    code: 'MV',
    dial_code: '+960',
  },
  {
    NameEnUS: 'Mali',
    nameFaIR: 'مالی',
    code: 'ML',
    dial_code: '+223',
  },
  {
    NameEnUS: 'Malta',
    nameFaIR: 'مالت',
    code: 'MT',
    dial_code: '+356',
  },
  {
    NameEnUS: 'Marshall Islands',
    nameFaIR: 'جزایر مارشال',
    code: 'MH',
    dial_code: '+692',
  },
  {
    NameEnUS: 'Mauritania',
    nameFaIR: 'موریتانی',
    code: 'MR',
    dial_code: '+222',
  },
  {
    NameEnUS: 'Mauritius',
    nameFaIR: 'موریس',
    code: 'MU',
    dial_code: '+230',
  },
  {
    NameEnUS: 'Mexico',
    nameFaIR: 'مکزیک',
    code: 'MX',
    dial_code: '+52',
  },
  {
    NameEnUS: 'Micronesia',
    nameFaIR: 'میکرونزی',
    code: 'FM',
    dial_code: '+691',
  },
  {
    NameEnUS: 'Moldova',
    nameFaIR: 'مولداوی',
    code: 'MD',
    dial_code: '+373',
  },
  {
    NameEnUS: 'Monaco',
    nameFaIR: 'موناکو',
    code: 'MC',
    dial_code: '+377',
  },
  {
    NameEnUS: 'Mongolia',
    nameFaIR: 'مغولستان',
    code: 'MN',
    dial_code: '+976',
  },
  {
    NameEnUS: 'Montenegro',
    nameFaIR: 'مونته‌نگرو',
    code: 'ME',
    dial_code: '+382',
  },
  {
    NameEnUS: 'Morocco',
    nameFaIR: 'مراکش',
    code: 'MA',
    dial_code: '+212',
  },
  {
    NameEnUS: 'Mozambique',
    nameFaIR: 'موزامبیک',
    code: 'MZ',
    dial_code: '+258',
  },
  {
    NameEnUS: 'Myanmar (formerly Burma)',
    nameFaIR: 'میانمار (برمه)',
    code: 'MM',
    dial_code: '+95',
  },
  {
    NameEnUS: 'Namibia',
    nameFaIR: 'نامیبیا',
    code: 'NA',
    dial_code: '+264',
  },
  {
    NameEnUS: 'Nauru',
    nameFaIR: 'نائورو',
    code: 'NR',
    dial_code: '+674',
  },
  {
    NameEnUS: 'Nepal',
    nameFaIR: 'نپال',
    code: 'NP',
    dial_code: '+977',
  },
  {
    NameEnUS: 'Netherlands',
    nameFaIR: 'هلند',
    code: 'NL',
    dial_code: '+31',
  },
  {
    NameEnUS: 'New Zealand',
    nameFaIR: 'نیوزیلند',
    code: 'NZ',
    dial_code: '+64',
  },
  {
    NameEnUS: 'Nicaragua',
    nameFaIR: 'نیکاراگوئه',
    code: 'NI',
    dial_code: '+505',
  },
  {
    NameEnUS: 'Niger',
    nameFaIR: 'نیجر',
    code: 'NE',
    dial_code: '+227',
  },
  {
    NameEnUS: 'Nigeria',
    nameFaIR: 'نیجریه',
    code: 'NG',
    dial_code: '+234',
  },
  {
    NameEnUS: 'North Korea',
    nameFaIR: 'کره شمالی',
    code: 'KP',
    dial_code: '+850',
  },
  {
    NameEnUS: 'North Macedonia',
    nameFaIR: 'مقدونیه شمالی',
    code: 'MK',
    dial_code: '+389',
  },
  {
    NameEnUS: 'Norway',
    nameFaIR: 'نروژ',
    code: 'NO',
    dial_code: '+47',
  },
  {
    NameEnUS: 'Oman',
    nameFaIR: 'عمان',
    code: 'OM',
    dial_code: '+968',
  },
  {
    NameEnUS: 'Pakistan',
    nameFaIR: 'پاکستان',
    code: 'PK',
    dial_code: '+92',
  },
  {
    NameEnUS: 'Palau',
    nameFaIR: 'پالائو',
    code: 'PW',
    dial_code: '+680',
  },
  {
    NameEnUS: 'Panama',
    nameFaIR: 'پاناما',
    code: 'PA',
    dial_code: '+507',
  },
  {
    NameEnUS: 'Papua New Guinea',
    nameFaIR: 'پاپوا گینه نو',
    code: 'PG',
    dial_code: '+675',
  },
  {
    NameEnUS: 'Paraguay',
    nameFaIR: 'پاراگوئه',
    code: 'PY',
    dial_code: '+595',
  },
  {
    NameEnUS: 'Peru',
    nameFaIR: 'پرو',
    code: 'PE',
    dial_code: '+51',
  },
  {
    NameEnUS: 'Philippines',
    nameFaIR: 'فیلیپین',
    code: 'PH',
    dial_code: '+63',
  },
  {
    NameEnUS: 'Poland',
    nameFaIR: 'لهستان',
    code: 'PL',
    dial_code: '+48',
  },
  {
    NameEnUS: 'Portugal',
    nameFaIR: 'پرتغال',
    code: 'PT',
    dial_code: '+351',
  },
  {
    NameEnUS: 'Qatar',
    nameFaIR: 'قطر',
    code: 'QA',
    dial_code: '+974',
  },
  {
    NameEnUS: 'Romania',
    nameFaIR: 'رومانی',
    code: 'RO',
    dial_code: '+40',
  },
  {
    NameEnUS: 'Russia',
    nameFaIR: 'روسیه',
    code: 'RU',
    dial_code: '+7',
  },
  {
    NameEnUS: 'Rwanda',
    nameFaIR: 'رواندا',
    code: 'RW',
    dial_code: '+250',
  },
  {
    NameEnUS: 'Saint Kitts and Nevis',
    nameFaIR: 'سنت کیتس و نویس',
    code: 'KN',
    dial_code: '+1',
  },
  {
    NameEnUS: 'Saint Lucia',
    nameFaIR: 'سنت لوسیا',
    code: 'LC',
    dial_code: '+1',
  },
  {
    NameEnUS: 'Saint Vincent and the Grenadines',
    nameFaIR: 'سنت وینسنت و گرنادین‌ها',
    code: 'VC',
    dial_code: '+1',
  },
  {
    NameEnUS: 'Samoa',
    nameFaIR: 'ساموا',
    code: 'WS',
    dial_code: '+685',
  },
  {
    NameEnUS: 'San Marino',
    nameFaIR: 'سان مارینو',
    code: 'SM',
    dial_code: '+378',
  },
  {
    NameEnUS: 'Sao Tome and Principe',
    nameFaIR: 'سائوتومه و پرنسیپ',
    code: 'ST',
    dial_code: '+239',
  },
  {
    NameEnUS: 'Saudi Arabia',
    nameFaIR: 'عربستان سعودی',
    code: 'SA',
    dial_code: '+966',
  },
  {
    NameEnUS: 'Senegal',
    nameFaIR: 'سنگال',
    code: 'SN',
    dial_code: '+221',
  },
  {
    NameEnUS: 'Serbia',
    nameFaIR: 'صربستان',
    code: 'RS',
    dial_code: '+381',
  },
  {
    NameEnUS: 'Seychelles',
    nameFaIR: 'سیشل',
    code: 'SC',
    dial_code: '+248',
  },
  {
    NameEnUS: 'Sierra Leone',
    nameFaIR: 'سیرالئون',
    code: 'SL',
    dial_code: '+232',
  },
  {
    NameEnUS: 'Singapore',
    nameFaIR: 'سنگاپور',
    code: 'SG',
    dial_code: '+65',
  },
  {
    NameEnUS: 'Slovakia',
    nameFaIR: 'اسلواکی',
    code: 'SK',
    dial_code: '+421',
  },
  {
    NameEnUS: 'Slovenia',
    nameFaIR: 'اسلوونی',
    code: 'SI',
    dial_code: '+386',
  },
  {
    NameEnUS: 'Solomon Islands',
    nameFaIR: 'جزایر سلیمان',
    code: 'SB',
    dial_code: '+677',
  },
  {
    NameEnUS: 'Somalia',
    nameFaIR: 'سومالی',
    code: 'SO',
    dial_code: '+252',
  },
  {
    NameEnUS: 'South Africa',
    nameFaIR: 'آفریقای جنوبی',
    code: 'ZA',
    dial_code: '+27',
  },
  {
    NameEnUS: 'South Korea',
    nameFaIR: 'کره جنوبی',
    code: 'KR',
    dial_code: '+82',
  },
  {
    NameEnUS: 'South Sudan',
    nameFaIR: 'سودان جنوبی',
    code: 'SS',
    dial_code: '+211',
  },
  {
    NameEnUS: 'Spain',
    nameFaIR: 'اسپانیا',
    code: 'ES',
    dial_code: '+34',
  },
  {
    NameEnUS: 'Sri Lanka',
    nameFaIR: 'سری‌لانکا',
    code: 'LK',
    dial_code: '+94',
  },
  {
    NameEnUS: 'Sudan',
    nameFaIR: 'سودان',
    code: 'SD',
    dial_code: '+249',
  },
  {
    NameEnUS: 'Suriname',
    nameFaIR: 'سورینام',
    code: 'SR',
    dial_code: '+597',
  },
  {
    NameEnUS: 'Sweden',
    nameFaIR: 'سوئد',
    code: 'SE',
    dial_code: '+46',
  },
  {
    NameEnUS: 'Switzerland',
    nameFaIR: 'سوئیس',
    code: 'CH',
    dial_code: '+41',
  },
  {
    NameEnUS: 'Syria',
    nameFaIR: 'سوریه',
    code: 'SY',
    dial_code: '+963',
  },
  {
    NameEnUS: 'Taiwan',
    nameFaIR: 'تایوان',
    code: 'TW',
    dial_code: '+886',
  },
  {
    NameEnUS: 'Tajikistan',
    nameFaIR: 'تاجیکستان',
    code: 'TJ',
    dial_code: '+992',
  },
  {
    NameEnUS: 'Tanzania',
    nameFaIR: 'تانزانیا',
    code: 'TZ',
    dial_code: '+255',
  },
  {
    NameEnUS: 'Thailand',
    nameFaIR: 'تایلند',
    code: 'TH',
    dial_code: '+66',
  },
  {
    NameEnUS: 'Timor-Leste',
    nameFaIR: 'تیمور شرقی',
    code: 'TL',
    dial_code: '+670',
  },
  {
    NameEnUS: 'Togo',
    nameFaIR: 'توگو',
    code: 'TG',
    dial_code: '+228',
  },
  {
    NameEnUS: 'Tonga',
    nameFaIR: 'تونگا',
    code: 'TO',
    dial_code: '+676',
  },
  {
    NameEnUS: 'Trinidad and Tobago',
    nameFaIR: 'ترینیداد و توباگو',
    code: 'TT',
    dial_code: '+1',
  },
  {
    NameEnUS: 'Tunisia',
    nameFaIR: 'تونس',
    code: 'TN',
    dial_code: '+216',
  },
  {
    NameEnUS: 'Turkey',
    nameFaIR: 'ترکیه',
    code: 'TR',
    dial_code: '+90',
  },
  {
    NameEnUS: 'Turkmenistan',
    nameFaIR: 'ترکمنستان',
    code: 'TM',
    dial_code: '+993',
  },
  {
    NameEnUS: 'Tuvalu',
    nameFaIR: 'تووالو',
    code: 'TV',
    dial_code: '+688',
  },
  {
    NameEnUS: 'Uganda',
    nameFaIR: 'اوگاندا',
    code: 'UG',
    dial_code: '+256',
  },
  {
    NameEnUS: 'Ukraine',
    nameFaIR: 'اوکراین',
    code: 'UA',
    dial_code: '+380',
  },
  {
    NameEnUS: 'United Arab Emirates',
    nameFaIR: 'امارات متحده عربی',
    code: 'AE',
    dial_code: '+971',
  },
  {
    NameEnUS: 'United Kingdom',
    nameFaIR: 'بریتانیا',
    code: 'GB',
    dial_code: '+44',
  },
  {
    NameEnUS: 'United States',
    nameFaIR: 'ایالات متحده',
    code: 'US',
    dial_code: '+1',
  },
  {
    NameEnUS: 'Uruguay',
    nameFaIR: 'اروگوئه',
    code: 'UY',
    dial_code: '+598',
  },
  {
    NameEnUS: 'Uzbekistan',
    nameFaIR: 'ازبکستان',
    code: 'UZ',
    dial_code: '+998',
  },
  {
    NameEnUS: 'Vanuatu',
    nameFaIR: 'وانواتو',
    code: 'VU',
    dial_code: '+678',
  },
  {
    NameEnUS: 'Venezuela',
    nameFaIR: 'ونزوئلا',
    code: 'VE',
    dial_code: '+58',
  },
  {
    NameEnUS: 'Vietnam',
    nameFaIR: 'ویتنام',
    code: 'VN',
    dial_code: '+84',
  },
  {
    NameEnUS: 'Yemen',
    nameFaIR: 'یمن',
    code: 'YE',
    dial_code: '+967',
  },
  {
    NameEnUS: 'Zambia',
    nameFaIR: 'زامبیا',
    code: 'ZM',
    dial_code: '+260',
  },
  {
    NameEnUS: 'Zimbabwe',
    nameFaIR: 'زیمبابوه',
    code: 'ZW',
    dial_code: '+263',
  },
]
