export const useCountries = () => [
  {
    NameEnUS: 'Afghanistan',
    nameFaIR: 'افغانستان',
    code: 'AF',
    dial_code: '+93',
    flag: 'icon-[emojione--flag-for-afghanistan]',
  },
  {
    NameEnUS: 'Albania',
    nameFaIR: 'البانیا',
    code: 'AL',
    dial_code: '+355',
    flag: 'icon-[emojione--flag-for-albania]',
  },
  {
    NameEnUS: 'Algeria',
    nameFaIR: 'الجزایر',
    code: 'DZ',
    dial_code: '+213',
    flag: 'icon-[emojione--flag-for-algeria]',
  },
  {
    NameEnUS: 'Andorra',
    nameFaIR: 'آندورا',
    code: 'AD',
    dial_code: '+376',
    flag: 'icon-[emojione--flag-for-andorra]',
  },
  {
    NameEnUS: 'Angola',
    nameFaIR: 'آنگولا',
    code: 'AO',
    dial_code: '+244',
    flag: 'icon-[emojione--flag-for-angola]',
  },
  {
    NameEnUS: 'Antigua and Barbuda',
    nameFaIR: 'آنتیگوا و باربودا',
    code: 'AG',
    dial_code: '+1',
    flag: 'icon-[emojione--flag-for-antigua-and-barbuda]',
  },
  {
    NameEnUS: 'Argentina',
    nameFaIR: 'آرژانتین',
    code: 'AR',
    dial_code: '+54',
    flag: 'icon-[emojione--flag-for-argentina]',
  },
  {
    NameEnUS: 'Armenia',
    nameFaIR: 'ارمنستان',
    code: 'AM',
    dial_code: '+374',
    flag: 'icon-[emojione--flag-for-armenia]',
  },
  {
    NameEnUS: 'Australia',
    nameFaIR: 'استرالیا',
    code: 'AU',
    dial_code: '+61',
    flag: 'icon-[emojione--flag-for-australia]',
  },
  {
    NameEnUS: 'Austria',
    nameFaIR: 'اتریش',
    code: 'AT',
    dial_code: '+43',
    flag: 'icon-[emojione--flag-for-austria]',
  },
  {
    NameEnUS: 'Azerbaijan',
    nameFaIR: 'آذربایجان',
    code: 'AZ',
    dial_code: '+994',
    flag: 'icon-[emojione--flag-for-azerbaijan]',
  },
  {
    NameEnUS: 'Bahamas',
    nameFaIR: 'باهاما',
    code: 'BS',
    dial_code: '+1',
    flag: 'icon-[emojione--flag-for-bahamas]',
  },
  {
    NameEnUS: 'Bahrain',
    nameFaIR: 'بحرین',
    code: 'BH',
    dial_code: '+973',
    flag: 'icon-[emojione--flag-for-bahrain]',
  },
  {
    NameEnUS: 'Bangladesh',
    nameFaIR: 'بنگلادش',
    code: 'BD',
    dial_code: '+880',
    flag: 'icon-[emojione--flag-for-bangladesh]',
  },
  {
    NameEnUS: 'Barbados',
    nameFaIR: 'باربادوس',
    code: 'BB',
    dial_code: '+1',
    flag: 'icon-[emojione--flag-for-barbados]',
  },
  {
    NameEnUS: 'Belarus',
    nameFaIR: 'بلاروس',
    code: 'BY',
    dial_code: '+375',
    flag: 'icon-[emojione--flag-for-flag-north-macedonia]',
  },
  {
    NameEnUS: 'Belgium',
    nameFaIR: 'بلژیک',
    code: 'BE',
    dial_code: '+32',
    flag: 'icon-[emojione--flag-for-belgium]',
  },
  {
    NameEnUS: 'Belize',
    nameFaIR: 'بلیز',
    code: 'BZ',
    dial_code: '+501',
    flag: 'icon-[emojione--flag-for-belize]',
  },
  {
    NameEnUS: 'Benin',
    nameFaIR: 'بنین',
    code: 'BJ',
    dial_code: '+229',
    flag: 'icon-[emojione--flag-for-benin]',
  },
  {
    NameEnUS: 'Bhutan',
    nameFaIR: 'بوتان',
    code: 'BT',
    dial_code: '+975',
    flag: 'icon-[emojione--flag-for-bhutan]',
  },
  {
    NameEnUS: 'Bolivia',
    nameFaIR: 'بولیوی',
    code: 'BO',
    dial_code: '+591',
    flag: 'icon-[emojione--flag-for-bolivia]',
  },
  {
    NameEnUS: 'Bosnia and Herzegovina',
    nameFaIR: 'بوسنی و هرزگوین',
    code: 'BA',
    dial_code: '+387',
    flag: 'icon-[emojione--flag-for-bosnia-and-herzegovina]',
  },
  {
    NameEnUS: 'Botswana',
    nameFaIR: 'بوتسوانا',
    code: 'BW',
    dial_code: '+267',
    flag: 'icon-[emojione--flag-for-botswana]',
  },
  {
    NameEnUS: 'Brazil',
    nameFaIR: 'برزیل',
    code: 'BR',
    dial_code: '+55',
    flag: 'icon-[emojione--flag-for-brazil]',
  },
  {
    NameEnUS: 'Brunei',
    nameFaIR: 'برونئی',
    code: 'BN',
    dial_code: '+673',
    flag: 'icon-[emojione--flag-for-brunei]',
  },
  {
    NameEnUS: 'Bulgaria',
    nameFaIR: 'بلغارستان',
    code: 'BG',
    dial_code: '+359',
    flag: 'icon-[emojione--flag-for-bulgaria]',
  },
  {
    NameEnUS: 'Burkina Faso',
    nameFaIR: 'بورکینافاسو',
    code: 'BF',
    dial_code: '+226',
    flag: 'icon-[emojione--flag-for-burkina-faso]',
  },
  {
    NameEnUS: 'Burundi',
    nameFaIR: 'بروندی',
    code: 'BI',
    dial_code: '+257',
    flag: 'icon-[emojione--flag-for-burundi]',
  },
  {
    NameEnUS: 'Cabo Verde',
    nameFaIR: 'کیپ ورد',
    code: 'CV',
    dial_code: '+238',
    flag: 'icon-[emojione--flag-for-cape-verde]',
  },
  {
    NameEnUS: 'Cambodia',
    nameFaIR: 'کامبوج',
    code: 'KH',
    dial_code: '+855',
    flag: 'icon-[emojione--flag-for-cambodia]',
  },
  {
    NameEnUS: 'Cameroon',
    nameFaIR: 'کامرون',
    code: 'CM',
    dial_code: '+237',
    flag: 'icon-[emojione--flag-for-cameroon]',
  },
  {
    NameEnUS: 'Canada',
    nameFaIR: 'کانادا',
    code: 'CA',
    dial_code: '+1',
    flag: 'icon-[emojione--flag-for-canada]',
  },
  {
    NameEnUS: 'Central African Republic',
    nameFaIR: 'جمهوری افریقای مرکزی',
    code: 'CF',
    dial_code: '+236',
    flag: 'icon-[emojione--flag-for-central-african-republic]',
  },
  {
    NameEnUS: 'Chad',
    nameFaIR: 'چاد',
    code: 'TD',
    dial_code: '+235',
    flag: 'icon-[emojione--flag-for-chad]',
  },
  {
    NameEnUS: 'Chile',
    nameFaIR: 'شیلی',
    code: 'CL',
    dial_code: '+56',
    flag: 'icon-[emojione--flag-for-chile]',
  },
  {
    NameEnUS: 'China',
    nameFaIR: 'چین',
    code: 'CN',
    dial_code: '+86',
    flag: 'icon-[emojione--flag-for-china]',
  },
  {
    NameEnUS: 'Colombia',
    nameFaIR: 'کلمبیا',
    code: 'CO',
    dial_code: '+57',
    flag: 'icon-[emojione--flag-for-colombia]',
  },
  {
    NameEnUS: 'Comoros',
    nameFaIR: 'کومور',
    code: 'KM',
    dial_code: '+269',
    flag: 'icon-[emojione--flag-for-flag-comoros]',
  },
  {
    NameEnUS: 'Congo (Congo-Brazzaville)',
    nameFaIR: 'کنگو (برازاویل)',
    code: 'CG',
    dial_code: '+242',
    flag: 'icon-[emojione--flag-for-flag-congo-brazzaville]',
  },
  {
    NameEnUS: 'Costa Rica',
    nameFaIR: 'کاستاریکا',
    code: 'CR',
    dial_code: '+506',
    flag: 'icon-[emojione--flag-for-flag-costa-rica]',
  },
  {
    NameEnUS: 'Croatia',
    nameFaIR: 'کرواسی',
    code: 'HR',
    dial_code: '+385',
    flag: 'icon-[emojione--flag-for-flag-croatia]',
  },
  {
    NameEnUS: 'Cuba',
    nameFaIR: 'کوبا',
    code: 'CU',
    dial_code: '+53',
    flag: 'icon-[emojione--flag-for-flag-cuba]',
  },
  {
    NameEnUS: 'Cyprus',
    nameFaIR: 'قبرس',
    code: 'CY',
    dial_code: '+357',
    flag: 'icon-[emojione--flag-for-flag-cyprus]',
  },
  {
    NameEnUS: 'Czechia (Czech Republic)',
    nameFaIR: 'جمهوری چک',
    code: 'CZ',
    dial_code: '+420',
    flag: 'icon-[emojione--flag-for-czechia]',
  },
  {
    NameEnUS: 'Democratic Republic of the Congo',
    nameFaIR: 'جمهوری دموکراتیک کنگو',
    code: 'CD',
    dial_code: '+243',
    flag: 'icon-[emojione--flag-for-congo-kinshasa]',
  },
  {
    NameEnUS: 'Denmark',
    nameFaIR: 'دانمارک',
    code: 'DK',
    dial_code: '+45',
    flag: 'icon-[emojione--flag-for-flag-denmark]',
  },
  {
    NameEnUS: 'Djibouti',
    nameFaIR: 'جیبوتی',
    code: 'DJ',
    dial_code: '+253',
    flag: 'icon-[emojione--flag-for-djibouti]',
  },
  {
    NameEnUS: 'Dominica',
    nameFaIR: 'دومینیکا',
    code: 'DM',
    dial_code: '+1',
    flag: 'icon-[emojione--flag-for-dominica]',
  },
  {
    NameEnUS: 'Dominican Republic',
    nameFaIR: 'جمهوری دومینیکن',
    code: 'DO',
    dial_code: '+1',
    flag: 'icon-[emojione--flag-for-dominican-republic]',
  },
  {
    NameEnUS: 'Ecuador',
    nameFaIR: 'اکوادور',
    code: 'EC',
    dial_code: '+593',
    flag: 'icon-[emojione--flag-for-ecuador]',
  },
  {
    NameEnUS: 'Egypt',
    nameFaIR: 'مصر',
    code: 'EG',
    dial_code: '+20',
    flag: 'icon-[emojione--flag-for-egypt]',
  },
  {
    NameEnUS: 'El Salvador',
    nameFaIR: 'السالوادور',
    code: 'SV',
    dial_code: '+503',
    flag: 'icon-[emojione--flag-for-el-salvador]',
  },
  {
    NameEnUS: 'Equatorial Guinea',
    nameFaIR: 'گینه استوایی',
    code: 'GQ',
    dial_code: '+240',
    flag: 'icon-[emojione--flag-for-equatorial-guinea]',
  },
  {
    NameEnUS: 'Eritrea',
    nameFaIR: 'اریتره',
    code: 'ER',
    dial_code: '+291',
    flag: 'icon-[emojione--flag-for-eritrea]',
  },
  {
    NameEnUS: 'Estonia',
    nameFaIR: 'استونی',
    code: 'EE',
    dial_code: '+372',
    flag: 'icon-[emojione--flag-for-estonia]',
  },
  {
    NameEnUS: 'Eswatini(fmr.Swaziland)',
    nameFaIR: 'اسواتینی',
    code: 'SZ',
    dial_code: '+268',
    flag: 'icon-[emojione--flag-for-flag-eswatini]',
  },
  {
    NameEnUS: 'Ethiopia',
    nameFaIR: 'اتیوپی',
    code: 'ET',
    dial_code: '+251',
    flag: 'icon-[emojione--flag-for-ethiopia]',
  },
  {
    NameEnUS: 'Fiji',
    nameFaIR: 'فیجی',
    code: 'FJ',
    dial_code: '+679',
    flag: 'icon-[emojione--flag-for-fiji]',
  },
  {
    NameEnUS: 'Finland',
    nameFaIR: 'فنلاند',
    code: 'FI',
    dial_code: '+358',
    flag: 'icon-[emojione--flag-for-finland]',
  },
  {
    NameEnUS: 'France',
    nameFaIR: 'فرانسه',
    code: 'FR',
    dial_code: '+33',
    flag: 'icon-[emojione--flag-for-france]',
  },
  {
    NameEnUS: 'Gabon',
    nameFaIR: 'گابون',
    code: 'GA',
    dial_code: '+241',
    flag: 'icon-[emojione--flag-for-gabon]',
  },
  {
    NameEnUS: 'Gambia',
    nameFaIR: 'گامبیا',
    code: 'GM',
    dial_code: '+220',
    flag: 'icon-[emojione--flag-for-gambia]',
  },
  {
    NameEnUS: 'Georgia',
    nameFaIR: 'گرجستان',
    code: 'GE',
    dial_code: '+995',
    flag: 'icon-[emojione--flag-for-georgia]',
  },
  {
    NameEnUS: 'Germany',
    nameFaIR: 'آلمان',
    code: 'DE',
    dial_code: '+49',
    flag: 'icon-[emojione--flag-for-germany]',
  },
  {
    NameEnUS: 'Ghana',
    nameFaIR: 'غنا',
    code: 'GH',
    dial_code: '+233',
    flag: 'icon-[emojione--flag-for-ghana]',
  },
  {
    NameEnUS: 'Greece',
    nameFaIR: 'یونان',
    code: 'GR',
    dial_code: '+30',
    flag: 'icon-[emojione--flag-for-greece]',
  },
  {
    NameEnUS: 'Grenada',
    nameFaIR: 'گرناڈا',
    code: 'GD',
    dial_code: '+1',
    flag: 'icon-[emojione--flag-for-grenada]',
  },
  {
    NameEnUS: 'Guatemala',
    nameFaIR: 'گواتمالا',
    code: 'GT',
    dial_code: '+502',
    flag: 'icon-[emojione--flag-for-guatemala]',
  },
  {
    NameEnUS: 'Guinea',
    nameFaIR: 'گینه',
    code: 'GN',
    dial_code: '+224',
    flag: 'icon-[emojione--flag-for-guinea]',
  },
  {
    NameEnUS: 'Guinea-Bissau',
    nameFaIR: 'گینه بیسائو',
    code: 'GW',
    dial_code: '+245',
    flag: 'icon-[emojione--flag-for-guinea-bissau]',
  },
  {
    NameEnUS: 'Guyana',
    nameFaIR: 'گویانا',
    code: 'GY',
    dial_code: '+592',
    flag: 'icon-[emojione--flag-for-guyana]',
  },
  {
    NameEnUS: 'Haiti',
    nameFaIR: 'هائیتی',
    code: 'HT',
    dial_code: '+509',
    flag: 'icon-[emojione--flag-for-haiti]',
  },
  {
    NameEnUS: 'Honduras',
    nameFaIR: 'هانڈورس',
    code: 'HN',
    dial_code: '+504',
    flag: 'icon-[emojione--flag-for-honduras]',
  },
  {
    NameEnUS: 'Hungary',
    nameFaIR: 'مجارستان',
    code: 'HU',
    dial_code: '+36',
    flag: 'icon-[emojione--flag-for-hungary]',
  },
  {
    NameEnUS: 'Iceland',
    nameFaIR: 'ایسلند',
    code: 'IS',
    dial_code: '+354',
    flag: 'icon-[emojione--flag-for-iceland]',
  },
  {
    NameEnUS: 'India',
    nameFaIR: 'هند',
    code: 'IN',
    dial_code: '+91',
    flag: 'icon-[emojione--flag-for-india]',
  },
  {
    NameEnUS: 'Indonesia',
    nameFaIR: 'اندونزی',
    code: 'ID',
    dial_code: '+62',
    flag: 'icon-[emojione--flag-for-indonesia]',
  },
  {
    NameEnUS: 'Iran',
    nameFaIR: 'ایران',
    code: 'IR',
    dial_code: '+98',
    flag: 'icon-[emojione--flag-for-iran]',
  },
  {
    NameEnUS: 'Iraq',
    nameFaIR: 'عراق',
    code: 'IQ',
    dial_code: '+964',
    flag: 'icon-[emojione--flag-for-iraq]',
  },
  {
    NameEnUS: 'Ireland',
    nameFaIR: 'ایرلند',
    code: 'IE',
    dial_code: '+353',
    flag: 'icon-[emojione--flag-for-ireland]',
  },
  {
    NameEnUS: 'Israel',
    nameFaIR: 'اسرائیل',
    code: 'IL',
    dial_code: '+972',
    flag: 'icon-[emojione--flag-for-israel]',
  },
  {
    NameEnUS: 'Italy',
    nameFaIR: 'ایتالیا',
    code: 'IT',
    dial_code: '+39',
    flag: 'icon-[emojione--flag-for-italy]',
  },
  {
    NameEnUS: 'Jamaica',
    nameFaIR: 'جمائیکا',
    code: 'JM',
    dial_code: '+1',
    flag: 'icon-[emojione--flag-for-jamaica]',
  },
  {
    NameEnUS: 'Japan',
    nameFaIR: 'ژاپن',
    code: 'JP',
    dial_code: '+81',
    flag: 'icon-[emojione--flag-for-japan]',
  },
  {
    NameEnUS: 'Jordan',
    nameFaIR: 'اردن',
    code: 'JO',
    dial_code: '+962',
    flag: 'icon-[emojione--flag-for-jordan]',
  },
  {
    NameEnUS: 'Kazakhstan',
    nameFaIR: 'قزاقستان',
    code: 'KZ',
    dial_code: '+7',
    flag: 'icon-[emojione--flag-for-kazakhstan]',
  },
  {
    NameEnUS: 'Kenya',
    nameFaIR: 'کنیا',
    code: 'KE',
    dial_code: '+254',
    flag: 'icon-[emojione--flag-for-kenya]',
  },
  {
    NameEnUS: 'Kiribati',
    nameFaIR: 'کیریباتی',
    code: 'KI',
    dial_code: '+686',
    flag: 'icon-[emojione--flag-for-kiribati]',
  },
  {
    NameEnUS: 'Kuwait',
    nameFaIR: 'کویت',
    code: 'KW',
    dial_code: '+965',
    flag: 'icon-[emojione--flag-for-kuwait]',
  },
  {
    NameEnUS: 'Kyrgyzstan',
    nameFaIR: 'قرقیزستان',
    code: 'KG',
    dial_code: '+996',
    flag: 'icon-[emojione--flag-for-kyrgyzstan]',
  },
  {
    NameEnUS: 'Laos',
    nameFaIR: 'لائوس',
    code: 'LA',
    dial_code: '+856',
    flag: 'icon-[emojione--flag-for-laos]',
  },
  {
    NameEnUS: 'Latvia',
    nameFaIR: 'لتونی',
    code: 'LV',
    dial_code: '+371',
    flag: 'icon-[emojione--flag-for-latvia]',
  },
  {
    NameEnUS: 'Lebanon',
    nameFaIR: 'لبنان',
    code: 'LB',
    dial_code: '+961',
    flag: 'icon-[emojione--flag-for-lebanon]',
  },
  {
    NameEnUS: 'Lesotho',
    nameFaIR: 'لسوتو',
    code: 'LS',
    dial_code: '+266',
    flag: 'icon-[emojione--flag-for-lesotho]',
  },
  {
    NameEnUS: 'Liberia',
    nameFaIR: 'لیبریا',
    code: 'LR',
    dial_code: '+231',
    flag: 'icon-[emojione--flag-for-liberia]',
  },
  {
    NameEnUS: 'Libya',
    nameFaIR: 'لیبی',
    code: 'LY',
    dial_code: '+218',
    flag: 'icon-[emojione--flag-for-libya]',
  },
  {
    NameEnUS: 'Liechtenstein',
    nameFaIR: 'لیختن‌اشتاین',
    code: 'LI',
    dial_code: '+423',
    flag: 'icon-[emojione--flag-for-liechtenstein]',
  },
  {
    NameEnUS: 'Lithuania',
    nameFaIR: 'لیتوانی',
    code: 'LT',
    dial_code: '+370',
    flag: 'icon-[emojione--flag-for-lithuania]',
  },
  {
    NameEnUS: 'Luxembourg',
    nameFaIR: 'لوکزامبورگ',
    code: 'LU',
    dial_code: '+352',
    flag: 'icon-[emojione--flag-for-luxembourg]',
  },
  {
    NameEnUS: 'Madagascar',
    nameFaIR: 'ماداگاسکار',
    code: 'MG',
    dial_code: '+261',
    flag: 'icon-[emojione--flag-for-madagascar]',
  },
  {
    NameEnUS: 'Malawi',
    nameFaIR: 'مالاوی',
    code: 'MW',
    dial_code: '+265',
    flag: 'icon-[emojione--flag-for-malawi]',
  },
  {
    NameEnUS: 'Malaysia',
    nameFaIR: 'مالزی',
    code: 'MY',
    dial_code: '+60',
    flag: 'icon-[emojione--flag-for-malaysia]',
  },
  {
    NameEnUS: 'Maldives',
    nameFaIR: 'مالدیو',
    code: 'MV',
    dial_code: '+960',
    flag: 'icon-[emojione--flag-for-maldives]',
  },
  {
    NameEnUS: 'Mali',
    nameFaIR: 'مالی',
    code: 'ML',
    dial_code: '+223',
    flag: 'icon-[emojione--flag-for-mali]',
  },
  {
    NameEnUS: 'Malta',
    nameFaIR: 'مالت',
    code: 'MT',
    dial_code: '+356',
    flag: 'icon-[emojione--flag-for-malta]',
  },
  {
    NameEnUS: 'Marshall Islands',
    nameFaIR: 'جزایر مارشال',
    code: 'MH',
    dial_code: '+692',
    flag: 'icon-[emojione--flag-for-marshall-islands]',
  },
  {
    NameEnUS: 'Mauritania',
    nameFaIR: 'موریتانی',
    code: 'MR',
    dial_code: '+222',
    flag: 'icon-[emojione--flag-for-mauritania]',
  },
  {
    NameEnUS: 'Mauritius',
    nameFaIR: 'موریس',
    code: 'MU',
    dial_code: '+230',
    flag: 'icon-[emojione--flag-for-mauritius]',
  },
  {
    NameEnUS: 'Mexico',
    nameFaIR: 'مکزیک',
    code: 'MX',
    dial_code: '+52',
    flag: 'icon-[emojione--flag-for-mexico]',
  },
  {
    NameEnUS: 'Micronesia',
    nameFaIR: 'میکرونزی',
    code: 'FM',
    dial_code: '+691',
    flag: 'icon-[emojione--flag-for-micronesia]',
  },
  {
    NameEnUS: 'Moldova',
    nameFaIR: 'مولداوی',
    code: 'MD',
    dial_code: '+373',
    flag: 'icon-[emojione--flag-for-moldova]',
  },
  {
    NameEnUS: 'Monaco',
    nameFaIR: 'موناکو',
    code: 'MC',
    dial_code: '+377',
    flag: 'icon-[emojione--flag-for-monaco]',
  },
  {
    NameEnUS: 'Mongolia',
    nameFaIR: 'مغولستان',
    code: 'MN',
    dial_code: '+976',
    flag: 'icon-[emojione--flag-for-mongolia]',
  },
  {
    NameEnUS: 'Montenegro',
    nameFaIR: 'مونته‌نگرو',
    code: 'ME',
    dial_code: '+382',
    flag: 'icon-[emojione--flag-for-montenegro]',
  },
  {
    NameEnUS: 'Morocco',
    nameFaIR: 'مراکش',
    code: 'MA',
    dial_code: '+212',
    flag: 'icon-[emojione--flag-for-morocco]',
  },
  {
    NameEnUS: 'Mozambique',
    nameFaIR: 'موزامبیک',
    code: 'MZ',
    dial_code: '+258',
    flag: 'icon-[emojione--flag-for-mozambique]',
  },
  {
    NameEnUS: 'Myanmar (formerly Burma)',
    nameFaIR: 'میانمار (برمه)',
    code: 'MM',
    dial_code: '+95',
    flag: 'icon-[emojione--flag-for-myanmar]',
  },
  {
    NameEnUS: 'Namibia',
    nameFaIR: 'نامیبیا',
    code: 'NA',
    dial_code: '+264',
    flag: 'icon-[emojione--flag-for-namibia]',
  },
  {
    NameEnUS: 'Nauru',
    nameFaIR: 'نائورو',
    code: 'NR',
    dial_code: '+674',
    flag: 'icon-[emojione--flag-for-nauru]',
  },
  {
    NameEnUS: 'Nepal',
    nameFaIR: 'نپال',
    code: 'NP',
    dial_code: '+977',
    flag: 'icon-[emojione--flag-for-nepal]',
  },
  {
    NameEnUS: 'Netherlands',
    nameFaIR: 'هلند',
    code: 'NL',
    dial_code: '+31',
    flag: 'icon-[emojione--flag-for-netherlands]',
  },
  {
    NameEnUS: 'New Zealand',
    nameFaIR: 'نیوزیلند',
    code: 'NZ',
    dial_code: '+64',
    flag: 'icon-[emojione--flag-for-new-zealand]',
  },
  {
    NameEnUS: 'Nicaragua',
    nameFaIR: 'نیکاراگوئه',
    code: 'NI',
    dial_code: '+505',
    flag: 'icon-[emojione--flag-for-nicaragua]',
  },
  {
    NameEnUS: 'Niger',
    nameFaIR: 'نیجر',
    code: 'NE',
    dial_code: '+227',
    flag: 'icon-[emojione--flag-for-niger]',
  },
  {
    NameEnUS: 'Nigeria',
    nameFaIR: 'نیجریه',
    code: 'NG',
    dial_code: '+234',
    flag: 'icon-[emojione--flag-for-nigeria]',
  },
  {
    NameEnUS: 'North Korea',
    nameFaIR: 'کره شمالی',
    code: 'KP',
    dial_code: '+850',
    flag: 'icon-[emojione--flag-for-north-korea]',
  },
  {
    NameEnUS: 'North Macedonia',
    nameFaIR: 'مقدونیه شمالی',
    code: 'MK',
    dial_code: '+389',
    flag: 'icon-[emojione--flag-for-flag-north-macedonia]',
  },
  {
    NameEnUS: 'Norway',
    nameFaIR: 'نروژ',
    code: 'NO',
    dial_code: '+47',
    flag: 'icon-[emojione--flag-for-norway]',
  },
  {
    NameEnUS: 'Oman',
    nameFaIR: 'عمان',
    code: 'OM',
    dial_code: '+968',
    flag: 'icon-[emojione--flag-for-oman]',
  },
  {
    NameEnUS: 'Pakistan',
    nameFaIR: 'پاکستان',
    code: 'PK',
    dial_code: '+92',
    flag: 'icon-[emojione--flag-for-pakistan]',
  },
  {
    NameEnUS: 'Palau',
    nameFaIR: 'پالائو',
    code: 'PW',
    dial_code: '+680',
    flag: 'icon-[emojione--flag-for-palau]',
  },
  {
    NameEnUS: 'Panama',
    nameFaIR: 'پاناما',
    code: 'PA',
    dial_code: '+507',
    flag: 'icon-[emojione--flag-for-panama]',
  },
  {
    NameEnUS: 'Papua New Guinea',
    nameFaIR: 'پاپوا گینه نو',
    code: 'PG',
    dial_code: '+675',
    flag: 'icon-[emojione--flag-for-papua-new-guinea]',
  },
  {
    NameEnUS: 'Paraguay',
    nameFaIR: 'پاراگوئه',
    code: 'PY',
    dial_code: '+595',
    flag: 'icon-[emojione--flag-for-paraguay]',
  },
  {
    NameEnUS: 'Peru',
    nameFaIR: 'پرو',
    code: 'PE',
    dial_code: '+51',
    flag: 'icon-[emojione--flag-for-peru]',
  },
  {
    NameEnUS: 'Philippines',
    nameFaIR: 'فیلیپین',
    code: 'PH',
    dial_code: '+63',
    flag: 'icon-[emojione--flag-for-philippines]',
  },
  {
    NameEnUS: 'Poland',
    nameFaIR: 'لهستان',
    code: 'PL',
    dial_code: '+48',
    flag: 'icon-[emojione--flag-for-poland]',
  },
  {
    NameEnUS: 'Portugal',
    nameFaIR: 'پرتغال',
    code: 'PT',
    dial_code: '+351',
    flag: 'icon-[emojione--flag-for-portugal]',
  },
  {
    NameEnUS: 'Qatar',
    nameFaIR: 'قطر',
    code: 'QA',
    dial_code: '+974',
    flag: 'icon-[emojione--flag-for-qatar]',
  },
  {
    NameEnUS: 'Romania',
    nameFaIR: 'رومانی',
    code: 'RO',
    dial_code: '+40',
    flag: 'icon-[emojione--flag-for-romania]',
  },
  {
    NameEnUS: 'Russia',
    nameFaIR: 'روسیه',
    code: 'RU',
    dial_code: '+7',
    flag: 'icon-[emojione--flag-for-russia]',
  },
  {
    NameEnUS: 'Rwanda',
    nameFaIR: 'رواندا',
    code: 'RW',
    dial_code: '+250',
    flag: 'icon-[emojione--flag-for-rwanda]',
  },
  {
    NameEnUS: 'Saint Kitts and Nevis',
    nameFaIR: 'سنت کیتس و نویس',
    code: 'KN',
    dial_code: '+1',
    flag: 'icon-[emojione--flag-for-st-kitts-and-nevis]',
  },
  {
    NameEnUS: 'Saint Lucia',
    nameFaIR: 'سنت لوسیا',
    code: 'LC',
    dial_code: '+1',
    flag: 'icon-[emojione--flag-for-st-lucia]',
  },
  {
    NameEnUS: 'Saint Vincent and the Grenadines',
    nameFaIR: 'سنت وینسنت و گرنادین‌ها',
    code: 'VC',
    dial_code: '+1',
    flag: 'icon-[emojione--flag-for-st-vincent-and-grenadines]',
  },
  {
    NameEnUS: 'Samoa',
    nameFaIR: 'ساموا',
    code: 'WS',
    dial_code: '+685',
    flag: 'icon-[emojione--flag-for-samoa]',
  },
  {
    NameEnUS: 'San Marino',
    nameFaIR: 'سان مارینو',
    code: 'SM',
    dial_code: '+378',
    flag: 'icon-[emojione--flag-for-san-marino]',
  },
  {
    NameEnUS: 'Sao Tome and Principe',
    nameFaIR: 'سائوتومه و پرنسیپ',
    code: 'ST',
    dial_code: '+239',
    flag: 'icon-[emojione--flag-for-sao-tome-and-principe]',
  },
  {
    NameEnUS: 'Saudi Arabia',
    nameFaIR: 'عربستان سعودی',
    code: 'SA',
    dial_code: '+966',
    flag: 'icon-[emojione--flag-for-saudi-arabia]',
  },
  {
    NameEnUS: 'Senegal',
    nameFaIR: 'سنگال',
    code: 'SN',
    dial_code: '+221',
    flag: 'icon-[emojione--flag-for-senegal]',
  },
  {
    NameEnUS: 'Serbia',
    nameFaIR: 'صربستان',
    code: 'RS',
    dial_code: '+381',
    flag: 'icon-[emojione--flag-for-serbia]',
  },
  {
    NameEnUS: 'Seychelles',
    nameFaIR: 'سیشل',
    code: 'SC',
    dial_code: '+248',
    flag: 'icon-[emojione--flag-for-seychelles]',
  },
  {
    NameEnUS: 'Sierra Leone',
    nameFaIR: 'سیرالئون',
    code: 'SL',
    dial_code: '+232',
    flag: 'icon-[emojione--flag-for-sierra-leone]',
  },
  {
    NameEnUS: 'Singapore',
    nameFaIR: 'سنگاپور',
    code: 'SG',
    dial_code: '+65',
    flag: 'icon-[emojione--flag-for-singapore]',
  },
  {
    NameEnUS: 'Slovakia',
    nameFaIR: 'اسلواکی',
    code: 'SK',
    dial_code: '+421',
    flag: 'icon-[emojione--flag-for-slovakia]',
  },
  {
    NameEnUS: 'Slovenia',
    nameFaIR: 'اسلوونی',
    code: 'SI',
    dial_code: '+386',
    flag: 'icon-[emojione--flag-for-slovenia]',
  },
  {
    NameEnUS: 'Solomon Islands',
    nameFaIR: 'جزایر سلیمان',
    code: 'SB',
    dial_code: '+677',
    flag: 'icon-[emojione--flag-for-solomon-islands]',
  },
  {
    NameEnUS: 'Somalia',
    nameFaIR: 'سومالی',
    code: 'SO',
    dial_code: '+252',
    flag: 'icon-[emojione--flag-for-somalia]',
  },
  {
    NameEnUS: 'South Africa',
    nameFaIR: 'آفریقای جنوبی',
    code: 'ZA',
    dial_code: '+27',
    flag: 'icon-[emojione--flag-for-south-africa]',
  },
  {
    NameEnUS: 'South Korea',
    nameFaIR: 'کره جنوبی',
    code: 'KR',
    dial_code: '+82',
    flag: 'icon-[emojione--flag-for-south-korea]',
  },
  {
    NameEnUS: 'South Sudan',
    nameFaIR: 'سودان جنوبی',
    code: 'SS',
    dial_code: '+211',
    flag: 'icon-[emojione--flag-for-south-sudan]',
  },
  {
    NameEnUS: 'Spain',
    nameFaIR: 'اسپانیا',
    code: 'ES',
    dial_code: '+34',
    flag: 'icon-[emojione--flag-for-spain]',
  },
  {
    NameEnUS: 'Sri Lanka',
    nameFaIR: 'سری‌لانکا',
    code: 'LK',
    dial_code: '+94',
    flag: 'icon-[emojione--flag-for-sri-lanka]',
  },
  {
    NameEnUS: 'Sudan',
    nameFaIR: 'سودان',
    code: 'SD',
    dial_code: '+249',
    flag: 'icon-[emojione--flag-for-sudan]',
  },
  {
    NameEnUS: 'Suriname',
    nameFaIR: 'سورینام',
    code: 'SR',
    dial_code: '+597',
    flag: 'icon-[emojione--flag-for-suriname]',
  },
  {
    NameEnUS: 'Sweden',
    nameFaIR: 'سوئد',
    code: 'SE',
    dial_code: '+46',
    flag: 'icon-[emojione--flag-for-sweden]',
  },
  {
    NameEnUS: 'Switzerland',
    nameFaIR: 'سوئیس',
    code: 'CH',
    dial_code: '+41',
    flag: 'icon-[emojione--flag-for-switzerland]',
  },
  {
    NameEnUS: 'Syria',
    nameFaIR: 'سوریه',
    code: 'SY',
    dial_code: '+963',
    flag: 'icon-[emojione--flag-for-syria]',
  },
  {
    NameEnUS: 'Taiwan',
    nameFaIR: 'تایوان',
    code: 'TW',
    dial_code: '+886',
    flag: 'icon-[emojione--flag-for-taiwan]',
  },
  {
    NameEnUS: 'Tajikistan',
    nameFaIR: 'تاجیکستان',
    code: 'TJ',
    dial_code: '+992',
    flag: 'icon-[emojione--flag-for-tajikistan]',
  },
  {
    NameEnUS: 'Tanzania',
    nameFaIR: 'تانزانیا',
    code: 'TZ',
    dial_code: '+255',
    flag: 'icon-[emojione--flag-for-tanzania]',
  },
  {
    NameEnUS: 'Thailand',
    nameFaIR: 'تایلند',
    code: 'TH',
    dial_code: '+66',
    flag: 'icon-[emojione--flag-for-thailand]',
  },
  {
    NameEnUS: 'Timor-Leste',
    nameFaIR: 'تیمور شرقی',
    code: 'TL',
    dial_code: '+670',
    flag: 'icon-[emojione--flag-for-timor-leste]',
  },
  {
    NameEnUS: 'Togo',
    nameFaIR: 'توگو',
    code: 'TG',
    dial_code: '+228',
    flag: 'icon-[emojione--flag-for-togo]',
  },
  {
    NameEnUS: 'Tonga',
    nameFaIR: 'تونگا',
    code: 'TO',
    dial_code: '+676',
    flag: 'icon-[emojione--flag-for-tonga]',
  },
  {
    NameEnUS: 'Trinidad and Tobago',
    nameFaIR: 'ترینیداد و توباگو',
    code: 'TT',
    dial_code: '+1',
    flag: 'icon-[emojione--flag-for-trinidad-and-tobago]',
  },
  {
    NameEnUS: 'Tunisia',
    nameFaIR: 'تونس',
    code: 'TN',
    dial_code: '+216',
    flag: 'icon-[emojione--flag-for-tunisia]',
  },
  {
    NameEnUS: 'Turkey',
    nameFaIR: 'ترکیه',
    code: 'TR',
    dial_code: '+90',
    flag: 'icon-[emojione--flag-for-turkey]',
  },
  {
    NameEnUS: 'Turkmenistan',
    nameFaIR: 'ترکمنستان',
    code: 'TM',
    dial_code: '+993',
    flag: 'icon-[emojione--flag-for-turkmenistan]',
  },
  {
    NameEnUS: 'Tuvalu',
    nameFaIR: 'تووالو',
    code: 'TV',
    dial_code: '+688',
    flag: 'icon-[emojione--flag-for-tuvalu]',
  },
  {
    NameEnUS: 'Uganda',
    nameFaIR: 'اوگاندا',
    code: 'UG',
    dial_code: '+256',
    flag: 'icon-[emojione--flag-for-uganda]',
  },
  {
    NameEnUS: 'Ukraine',
    nameFaIR: 'اوکراین',
    code: 'UA',
    dial_code: '+380',
    flag: 'icon-[emojione--flag-for-ukraine]',
  },
  {
    NameEnUS: 'United Arab Emirates',
    nameFaIR: 'امارات متحده عربی',
    code: 'AE',
    dial_code: '+971',
    flag: 'icon-[emojione--flag-for-united-arab-emirates]',
  },
  {
    NameEnUS: 'United Kingdom',
    nameFaIR: 'بریتانیا',
    code: 'GB',
    dial_code: '+44',
    flag: 'icon-[emojione--flag-for-united-kingdom]',
  },
  {
    NameEnUS: 'United States',
    nameFaIR: 'ایالات متحده',
    code: 'US',
    dial_code: '+1',
    flag: 'icon-[emojione--flag-for-united-states]',
  },
  {
    NameEnUS: 'Uruguay',
    nameFaIR: 'اروگوئه',
    code: 'UY',
    dial_code: '+598',
    flag: 'icon-[emojione--flag-for-uruguay]',
  },
  {
    NameEnUS: 'Uzbekistan',
    nameFaIR: 'ازبکستان',
    code: 'UZ',
    dial_code: '+998',
    flag: 'icon-[emojione--flag-for-uzbekistan]',
  },
  {
    NameEnUS: 'Vanuatu',
    nameFaIR: 'وانواتو',
    code: 'VU',
    dial_code: '+678',
    flag: 'icon-[emojione--flag-for-vanuatu]',
  },
  {
    NameEnUS: 'Venezuela',
    nameFaIR: 'ونزوئلا',
    code: 'VE',
    dial_code: '+58',
    flag: 'icon-[emojione--flag-for-venezuela]',
  },
  {
    NameEnUS: 'Vietnam',
    nameFaIR: 'ویتنام',
    code: 'VN',
    dial_code: '+84',
    flag: 'icon-[emojione--flag-for-vietnam]',
  },
  {
    NameEnUS: 'Yemen',
    nameFaIR: 'یمن',
    code: 'YE',
    dial_code: '+967',
    flag: 'icon-[emojione--flag-for-yemen]',
  },
  {
    NameEnUS: 'Zambia',
    nameFaIR: 'زامبیا',
    code: 'ZM',
    dial_code: '+260',
    flag: 'icon-[emojione--flag-for-zambia]',
  },
  {
    NameEnUS: 'Zimbabwe',
    nameFaIR: 'زیمبابوه',
    code: 'ZW',
    dial_code: '+263',
    flag: 'icon-[emojione--flag-for-zimbabwe]',
  },
]
